# Generated by Django 5.2.9 on 2025-12-22 06:11

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cursosrealizados",
            fields=[
                (
                    "idcursorealizado",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "nombrecurso",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("fechainicio", models.DateField()),
                ("fechafin", models.DateField(blank=True, null=True)),
                ("totalhoras", models.IntegerField()),
                (
                    "descripcioncurso",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("activarparaqueseveaenfront", models.BooleanField()),
            ],
            options={
                "db_table": "CURSOSREALIZADOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Datospersonales",
            fields=[
                ("idperfil", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "descripcionperfil",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("perfilactivo", models.IntegerField(blank=True, null=True)),
                (
                    "apellidos",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "nombres",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "nacionalidad",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "lugarnacimiento",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=60,
                        null=True,
                    ),
                ),
                ("fechanacimiento", models.DateField(blank=True, null=True)),
                (
                    "numerocedula",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "estadocivil",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "licenciaconducir",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "telefonoconvencional",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "telefonofijo",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "direcciontrabajo",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "direcciondomiciliaria",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "sitioweb",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=60,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "DATOSPERSONALES",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Experiencialaboral",
            fields=[
                (
                    "idexperiencilaboral",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "cargodesempenado",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "nombrempresa",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("fechainiciogestion", models.DateField()),
                ("fechafingestion", models.DateField(blank=True, null=True)),
                (
                    "descripcionfunciones",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("activarparaqueseveaenfront", models.BooleanField()),
            ],
            options={
                "db_table": "EXPERIENCIALABORAL",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Reconocimientos",
            fields=[
                (
                    "idreconocimiento",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "tiporeconocimiento",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("fechareconocimiento", models.DateField(blank=True, null=True)),
                (
                    "descripcionreconocimiento",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "entidadpatrocinadora",
                    models.CharField(
                        blank=True,
                        db_collation="SQL_Latin1_General_CP1_CI_AI",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "activarparaqueseveaenfront",
                    models.BooleanField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "RECONOCIMIENTOS",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[("ADMIN", "Administrador"), ("PERSONAL", "Personal")],
                        max_length=10,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
